spring:
  application:
    name: wa-user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      keyDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.value.default.type: org.wa.user.service.dto.user.UserRegisteredDto
      spring.json.trusted.packages: "org.wa.user.service.dto.user,java.util,java.lang"
      spring.json.use.type.headers: false
      spring.deserializer.value.error.handling: logAndContinue

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA:wa_user_service_db}
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    default-schema: ${DB_SCHEMA:wa_user_service_db}
    liquibase-schema: public
server:
  port: 8081

integration:
  auth-service:
    base-url: ${INTEGRATION_AUTH_SERVICE_BASE_URL:http://localhost:8080}
    timeout: 5000

auth-service:
  login-endpoint: "/v1/auth/login"
  accessToken-endpoint: "/v1/auth/token"
  refreshToken-endpoint: "/v1/auth/refresh"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

kafka:
  topics:
    user-registered: user.registered

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
  expiration-ms: ${JWT_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

encrypt:
  secret: ${ENCRYPT_SECRET}
  cipher-algorithm: ${CIPHER_ALGORITHM}
  secret-key-algorithm: ${SECRET_KEY_ALGORITHM}