spring:
  application:
    name: wa-user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    analytics-enabled: true

server:
  port: 8081

integration:
  auth-service:
    base-url: ${integration.auth-service.base-url}
    timeout: ${integration.auth-service.timeout}

auth-service:
  login-endpoint: ${auth-service.login-endpoint}
  accessToken-endpoint: ${auth-service.accessToken-endpoint}
  refreshToken-endpoint: ${auth-service.refreshToken-endpoint}