databaseChangeLog:
  - changeSet:
      id: 2025.10.30_005-set-default-values
      author: mihailov.pashka@yandex.ru
      changes:
        - addDefaultValue:
            tableName: users
            columnName: status
            defaultValue: "ACTIVE"

        - addDefaultValue:
            tableName: users
            columnName: created_at
            defaultValueComputed: CURRENT_TIMESTAMP

        - addDefaultValue:
            tableName: users
            columnName: modified_at
            defaultValueComputed: CURRENT_TIMESTAMP

        - addDefaultValue:
            tableName: connected_device
            columnName: is_active
            defaultValueBoolean: true

        - addDefaultValue:
            tableName: connected_device
            columnName: last_sync_at
            defaultValueComputed: CURRENT_TIMESTAMP